### ISSUE TITLE
Error getting IP address

### ISSUE THREAD

**Issue by petergerdes** [jlentink/go-transip-dyndns#1]
Script can't get the public IP Address from [https://www.ipify.org](url) API.

When running I encounter:
`FATAL - Error getting IP address. (Get "https://api6.ipify.org?format=json": dial tcp [2607:f2d8:4010:c::2]:443: connect: network is unreachable)`

Looking at [https://github.com/jlentink/go-transip-dyndns/blob/master/internal/gipify/get.go](url) on line 19, api is `https://api6.ipify.org?format=json` but [https://www.ipify.org](url) reference tells either `api.ipify.org` or `api64.ipify.org`

**Comment by jlentink** [comment]
Fixed download version v1.0.2 for the fix.
