### ISSUE TITLE
Could not update TXT record

### ISSUE THREAD

**Issue by hjheins** [jlentink/go-transip-dyndns#10]
Hi,

(English as not-dutch speakers may also read this)

First a big thank you for this script, it is REALLY useful!

I ran into the below:

❗  Could not update the record to update @.<domain.nl> [TXT] - template: content:1:35: executing "content" at <.IP4>: can't evaluate field IP4 in type transipClient.recordContent

my config:

[[record]]
hostname = "<domain.nl>"
entry = "@"
ttl = 60
type = "TXT"
content = "v=spf1 a:mx a:mail.<domain.nl> ip4:{{.IP4}} ip6:{{.IP6}} ~all"

Am I doing something wrong here, or is this a parsing issue in the code?

thanks,

Hendrik-Jan

**Comment by morepurplemorebetter** [comment]
The [example.go-transip-dyndns.toml](../blob/master/example.go-transip-dyndns.toml#L84) has the placeholders as `# for other records you can use the placeholders {{.IPv4}} and {{.IPv6}}`.

So most likely you are just missing the `v` to get the correct placeholder.

**Comment by hjheins** [comment]
Hi @morepurplemorebetter , thank you that was it. I completele missed the "v"  here.
Case closed
