### ISSUE TITLE
Could not update TXT record

### ISSUE THREAD

**Issue by hjheins** [jlentink/go-transip-dyndns#12]
I currently have 2 TXT records with "@" as name for the domain.
I only need to update one of them but I am guessing that because I have 2, the update will not work.
The error message is:

❗  Could not update the record to update @.<domainname>.nl [TXT] - Could not find match for DNS entry '@ 1 TXT'

Is there any way around this? Both of the entries are for the full domain. one of the 2 is this "google domain verification".

thanks.

**Comment by hjheins** [comment]
I ended up merging the 2 txt records into one, that seemed to have done the trick.

**Comment by JDunnio** [comment]
> I ended up merging the 2 txt records into one, that seemed to have done the trick.

I don't know if you have the same problem, but the ttl in the config is in seconds ... in the transip control panel it is in minutes, hours, days.

So a config of "@ 1 TXT" is impossible as that means 1 seconds ttl. Make it 60 is in the config.

The example config could be more clearer about that. Almost gave up after an hour :)

Thankts for this great docker container @jlentink !

**Comment by hjheins** [comment]
OK, merging here is no solution, I will have to change to another solution here.
This means that it is a bit tricky to define more than 1 TXT entry for the domain itself, maybe not even possible?

**Comment by jlentink** [comment]
Okay, I just checked the updating of the TXT records works. I could update it without an issue. However, I tried to make a solution to have multiple records be updated. That is not possible; I have no option to detect which record should be which.
