### ISSUE TITLE
Compile version for MIPS64

### ISSUE THREAD

**Issue by jorisscheppers** [jlentink/go-transip-dyndns#2]
I would like to run this on my Unifi USG, which has a MIPS64 architecture:
`admin@USG:~$ uname -srm`
`Linux 3.10.107-UBNT mips64`

Could you also build a MIPS64 release?

**Comment by jlentink** [comment]
Will do.

**Comment by jlentink** [comment]
Done. Download under the release new version will have the build. https://github.com/jlentink/go-transip-dyndns/releases/tag/v1.0.2
