### ISSUE TITLE
Bash file for use with Synology Task Scheduler

### ISSUE THREAD

**Issue by water1309** [jlentink/go-transip-dyndns#3]
This looks like an awesome little tool. I got it to work (mostly) on my Synology NAS.

For some reason the cronjob won't work. So I thought if I could add a bash file to the task scheduler (adding the link to the binary directly gives the error that it is not an executable file) it might work. However I can't figure out how to make the bash file. Do you have any pointers?

Thanks in advance!

**Comment by jlentink** [comment]
Can you add the error output in this ticket. And which build did you use.

**Comment by jlentink** [comment]
No feedback closing ticket.
