### ISSUE TITLE
Different dns records

### ISSUE THREAD

**Issue by andytuinman3** [jlentink/go-transip-dyndns#4]
Got it running for my domains in a Synology docker. Works great. 

But I also have a DNS spf txt record like: "v=spf1 ip4:IP_ADDRESS ~all". Which I also would like to update to the new address if possible. Is that something that is build in in this tool? \

**Comment by jlentink** [comment]
I will check.

**Comment by squadramunter** [comment]
I agree with @andytuinman3 for my mailserver it is very important that mail is send out correctly so it is not marked as spam.

I think this can be simply done by searching for @ to name and pointing to TXT record. In my case I only have one name with @ pointing to the TXT record. Maybe you can do something but this?

Greetings,

SquadraMunter

**Comment by jlentink** [comment]
Feature implemented now and available to download in v2.
