### ISSUE TITLE
Support for multiple domains

### ISSUE THREAD

**Issue by squadramunter** [jlentink/go-transip-dyndns#5]
Hi first I want to thank you for this awesome tool.

Second I like the idea of using this tool to automatically update the A record to the correct IP. But I also like to see support for multiple domains. I have 3 domains but when I add them double I can't run it.

The only workaround is to create a directory and run multiple programs alongside.

Would be great to see support for that.

**Comment by jlentink** [comment]
Thanks for the feedback.

It would be a good idea! Let me put that on the roadmap.

**Comment by squadramunter** [comment]
I searched in the API and it seems you can list all domains by using this command.

$allDomains = $api->domains()->getAll();

This is their PHP code API

**Comment by jlentink** [comment]
Feature implemented now and available to download in v2.
