### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by memen45** [jlentink/go-transip-dyndns#6]
Trying to install the tool, did the following steps, but am getting command not found error.
```
wget https://github.com/jlentink/go-transip-dyndns/releases/download/v1.0.3/go-transip-dyndns_Linux_x86_64.tar.gz
sudo tar xzvf go-transip-dyndns_Linux_x86_64.tar.gz
go-transip-dyndns validate
```

Now I have no idea how to proceed. Did I make a mistake or could you maybe point me to the standard procedure of installing these kind of binaries?

**Comment by jlentink** [comment]
Please follow the instruction on the Readme file and you should be fine. You can run it from everywhere on your system.

**Comment by memen45** [comment]
The first 5 steps are clear, however, the downloading/installing steps are not described. At step 6 the crontab has to be edited, however, I assume the binary has to be installed before that in order to work?

**Comment by jlentink** [comment]
Yes the binary can be where every you like. The config needs to be 

- in the same directory
- /etc
- /etc/go-transip-dyndns

filename is go-transip-dyndns.toml

Just download the bin which works for your system and place it somewhere and off you go.

**Comment by memen45** [comment]
Ah okay, thanks a lot. The manual part is working now. However, I think the cron is not working. I added the following line to the crontab
`0 * * * * /usr/local/bin/go-transip-dyndns > ~/go-transip-dyndns/go-transip-dyndns.log 2>&1`

But got the following in the log file:
`/bin/sh: 1: /usr/local/bin/go-transip-dyndns: not found`

I can run from `~/go-transip-dyndns/go-transip-dyndns` manually though.

**Comment by jlentink** [comment]
Well the hint is then also there.
The binary is not available in /usr/local/bin bit in your home directory
under go-transip-dyndns.

Move the binary to the correct location and ensure it is able to find the
config under /usr/local/bin an you are set.


Met vriendelijke groet, Kind regards,

--
[image: photo]
*Jason Lentink*
Technology Director Platforms, Big Builds & eCommerce Monk, MediaMonks

‭+31 6 11 72 12 01‬  <%E2%80%AD+31611721201%E2%80%AC>| ***@***.***

blog <https://www.mediamonks.com/blog> | mediamonks.com
<https://www.mediamonks.com/>
S4Capital <https://www.s4capital.com/> (SFOR)
<https://www.londonstockexchange.com/stock/SFOR/s4-capital-plc/company-page?lang=en>
<https://www.linkedin.com/in/jasonlentink/>
<https://www.instagram.com/mediamonks/>
<https://www.youtube.com/watch?v=18ht3EBa1m4>  <https://vimeo.com/263854900>

**Comment by memen45** [comment]
Thanks, so the files should be copied to /usr/local/bin directory. Went for the other solution:

`0 * * * * cd go-transip-dyndns && ./go-transip-dyndns > go-transip-dyndns.log 2>&1`
