### ISSUE TITLE
Init en update niet werkende voor @ record

### ISSUE THREAD

**Issue by Lexus123** [jlentink/go-transip-dyndns#9]
Zojuist `go install` gedaan en `go-transip-dyndns` valt te draaien. Echter liep ik tegen meerdere zaken aan:

1. In de setup staat dat men `go-transip-dyndns init` moet draaien om een configuratie bestand te maken. Dit bestand wordt nooit gemaakt. In plaats daarvan geeft het een error:

```
FATAL - Config File "go-transip-dyndns" Not Found in "[/etc /etc/go-transip-dyndns.d /home/ubuntu]"
```

Als ik dan de file handmatig aanmaak en `init` nog een keer draai krijg ik de error `❗  Config file already exists. exiting... Remove the old one to write a fresh one.`

2. Het updaten van `@` wil niet werken. Validate geeft een goede uitkomst. Ik zal beiden even hier neerzetten.

Output van `update` (met fake IP natuurlijk, want die gooi ik maar niet op Github)

```
DEBUG - Log level set to debug...
DEBUG - Found IP address. (799.788.777.766)
❗  Could not update the record to update @.somedomain.nl [A] - Error setting Dns Entries
```

Output van `validate`

```
DEBUG - Log level set to debug...
 - Verify access to API.
👍  Connection successful.
 - Verify IP fetch
DEBUG - Found IP address. (799.788.777.766)
👍  IPv4 fetch successful - 799.788.777.766.
👍  IPv6 disabled.
 - Verify access to domain(s)
👍  Found domain: somedomain.nl
    Renewal date: 2023-01-24 00:00:00 +0100 CET
DEBUG - Domain: {Tags:[] AuthCode:blablabla CancellationDate:0001-01-01 00:00:00 +0000 UTC CancellationStatus: IsDNSOnly:false IsTransferLocked:false IsWhitelabel:false Name:somedomain.nl RegistrationDate:2022-01-24 00:00:00 +0100 CET RenewalDate:2023-01-24 00:00:00 +0100 CET} - Verify target domain record(s)
DEBUG - Config record: {Hostname:somedomain.nl Entry:@ Content: TTL:60 Type:A}
DEBUG - Record: {Name:@ Expire:60 Type:A Content:37.97.254.27}
👍  Found record: @.somedomain.nl (A)
DEBUG - Record found details: {Hostname:somedomain.nl Entry:@ Content: TTL:60 Type:A}

```

**Comment by Lexus123** [comment]
Het bovenste was afkomstig van de master branch, maar als ik binary v2.0.1 geeft dezelfde uitkomst.

**Comment by Lexus123** [comment]
Het werkt wel voor een subdomain, maar niet voor een "@" record.

**Comment by jlentink** [comment]
Ik zal er naar kijken.

**Comment by jlentink** [comment]
Hi @Lexus123,

Ik heb even zitten testen maar ik kan het probleem niet repliceren.
Kan je wat meer informatie geven over of dit nog steeds gebeurd?

```DEBUG - Log level set to debug...
DEBUG - Found IP address. (99.99.99.99)
👍  Record still up to date: @.something.com [A]

Process finished with the exit code 0
```

**Comment by fevo21** [comment]
Hier aanvankelijk hetzelfde probleem met het aanmaken / updaten van een DNS record voor het root domain. Subdomain werkt zonder problemen.


```
docker-compose run --rm --entrypoint /usr/bin/go-transip-dyndns go-transip-dyndns -v create

Creating transip_go-transip-dyndns_run ... done
DEBUG - Log level set to debug...
  Found record not creating... (subdomain.mydomain.nl [A])
    To update these records use update.

DEBUG - Found IP address. (99.99.99.99)
  created record! @.mydomain.nl [A])
❗  Error creating record (Error setting Dns Entries)
```
Betreffende records uit configuratie:
```
[[record]]
hostname = "mydomain.nl"
entry = "subdomain"
ttl = 3600
type = "A"

[[record]]
hostname = "mydomain.nl"
entry = "@"
ttl = 3600
type = "A"
```

Ik denk dat bovenstaande fout komt omdat er nog een IP6 (AAAA) record is die naar een andere locatie verwijst. Na het verwijderen van de AAAA record in de portal van transIP werkte het updaten van het A record via de API wel. Wellicht is dat ook wat er bij @Lexus123 aan de hand is.

**Comment by Lexus123** [comment]
@fevo21 goede tip! Zal ik ergens deze week even proberen.
